// Package manifest provides the project-level configuration for code-minions.
// A project manifest (code-minions.yml) declares which packages to install,
// which assistant to target, and other project-level settings.
package manifest

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const (
	// FileName is the default manifest filename.
	FileName = "code-minions.yml"

	// headerComment is prepended to the YAML output.
	headerComment = "# Generated by code-minions init\n"
)

// ProjectManifest represents a code-minions.yml project configuration.
type ProjectManifest struct {
	Name      string   `yaml:"name"`
	Version   string   `yaml:"version,omitempty"`
	Assistant string   `yaml:"assistant,omitempty"`
	Packages  []string `yaml:"packages,omitempty"`
}

// DefaultPath returns the full path to code-minions.yml within the
// given target directory.
func DefaultPath(target string) string {
	return filepath.Join(target, FileName)
}

// Exists checks whether a code-minions.yml file exists at the given path.
// Returns (true, nil) if the file exists, (false, nil) if it does not,
// or (false, err) if the check failed (e.g. permission denied).
func Exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, fmt.Errorf("failed to check manifest: %w", err)
}

// Load reads and parses a code-minions.yml file at the given path.
// Returns a zero-value manifest if the file does not exist.
// Returns an error for I/O failures or invalid YAML.
func Load(path string) (*ProjectManifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &ProjectManifest{}, nil
		}
		return nil, fmt.Errorf("failed to read manifest: %w", err)
	}

	var m ProjectManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("failed to parse manifest: %w", err)
	}

	return &m, nil
}

// Save writes a ProjectManifest to the given path as YAML, preceded by a
// header comment. Parent directories are created if they do not exist.
func Save(path string, m *ProjectManifest) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("failed to marshal manifest: %w", err)
	}

	content := []byte(headerComment)
	content = append(content, data...)

	// Atomic write: write to a temp file in the same directory, then rename.
	// This avoids leaving a partially-written manifest if the process is
	// interrupted mid-write.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, content, 0644); err != nil {
		return fmt.Errorf("failed to write manifest: %w", err)
	}
	// os.Rename on Windows fails when the destination already exists.
	// Remove the target first to ensure the rename succeeds cross-platform.
	_ = os.Remove(path)
	if err := os.Rename(tmp, path); err != nil {
		// Clean up the temp file on rename failure.
		_ = os.Remove(tmp)
		return fmt.Errorf("failed to write manifest: %w", err)
	}

	return nil
}

// AddPackage appends a package name if not already present.
// Returns true if the package was added (false if already listed).
func (m *ProjectManifest) AddPackage(name string) bool {
	for _, p := range m.Packages {
		if p == name {
			return false
		}
	}
	m.Packages = append(m.Packages, name)
	return true
}

// RemovePackage removes a package name from the list.
// Returns true if the package was found and removed.
func (m *ProjectManifest) RemovePackage(name string) bool {
	for i, p := range m.Packages {
		if p == name {
			m.Packages = append(m.Packages[:i], m.Packages[i+1:]...)
			return true
		}
	}
	return false
}

// HasPackage checks whether a package is in the manifest's packages list.
func (m *ProjectManifest) HasPackage(name string) bool {
	for _, p := range m.Packages {
		if p == name {
			return true
		}
	}
	return false
}

// LoadResult contains the parsed manifest and any non-fatal warnings.
type LoadResult struct {
	Manifest *ProjectManifest
	Warnings []string
}

// LoadStrict reads a code-minions.yml and reports unknown fields as warnings.
// The manifest is still parsed and returned even when unknown fields exist.
// Returns a zero-value manifest (with no warnings) if the file does not exist.
func LoadStrict(path string) (*LoadResult, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &LoadResult{Manifest: &ProjectManifest{}}, nil
		}
		return nil, fmt.Errorf("failed to read manifest: %w", err)
	}

	// First pass: decode into struct (will silently ignore unknown fields)
	var m ProjectManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("failed to parse manifest: %w", err)
	}

	// Second pass: decode with KnownFields to detect unknown keys
	var warnings []string
	dec := yaml.NewDecoder(bytes.NewReader(data))
	dec.KnownFields(true)
	var strict ProjectManifest
	if err := dec.Decode(&strict); err != nil {
		// The error message from yaml.v3 lists the unknown field
		warnings = append(warnings, fmt.Sprintf("unknown field: %v", err))
	}

	return &LoadResult{Manifest: &m, Warnings: warnings}, nil
}

// Validate checks the manifest for semantic errors. It returns a list
// of problems found. validAssistants and validPackages are the known
// names to validate against; pass nil to skip those checks.
func (m *ProjectManifest) Validate(validAssistants, validPackages []string) []string {
	var problems []string

	if m.Name == "" {
		problems = append(problems, "name is required")
	}

	if m.Assistant != "" && len(validAssistants) > 0 {
		found := false
		for _, a := range validAssistants {
			if a == m.Assistant {
				found = true
				break
			}
		}
		if !found {
			problems = append(problems, fmt.Sprintf("unknown assistant %q", m.Assistant))
		}
	}

	if len(validPackages) > 0 {
		validSet := make(map[string]bool, len(validPackages))
		for _, p := range validPackages {
			validSet[p] = true
		}
		for _, p := range m.Packages {
			if !validSet[p] {
				problems = append(problems, fmt.Sprintf("unknown package %q", p))
			}
		}
	}

	return problems
}
