// Package manifest provides the project-level configuration for code-minions.
// A project manifest (code-minions.yml) declares which packages to install,
// which assistant to target, and other project-level settings.
//
// This is the minimal schema needed by the init command. Issue #95 will
// expand it with validation, unknown-field warnings, and integration
// with install/uninstall. The dependencies field (remote packages) is
// deliberately omitted until #83 lands.
package manifest

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

const (
	// FileName is the default manifest filename.
	FileName = "code-minions.yml"

	// headerComment is prepended to the YAML output.
	headerComment = "# Generated by code-minions init\n"
)

// ProjectManifest represents a code-minions.yml project configuration.
type ProjectManifest struct {
	Name      string   `yaml:"name"`
	Version   string   `yaml:"version,omitempty"`
	Assistant string   `yaml:"assistant,omitempty"`
	Packages  []string `yaml:"packages,omitempty"`
}

// DefaultPath returns the full path to code-minions.yml within the
// given target directory.
func DefaultPath(target string) string {
	return filepath.Join(target, FileName)
}

// Exists checks whether a code-minions.yml file exists at the given path.
// Returns (true, nil) if the file exists, (false, nil) if it does not,
// or (false, err) if the check failed (e.g. permission denied).
func Exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, fmt.Errorf("failed to check manifest: %w", err)
}

// Load reads and parses a code-minions.yml file at the given path.
// Returns a zero-value manifest if the file does not exist.
// Returns an error for I/O failures or invalid YAML.
func Load(path string) (*ProjectManifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return &ProjectManifest{}, nil
		}
		return nil, fmt.Errorf("failed to read manifest: %w", err)
	}

	var m ProjectManifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("failed to parse manifest: %w", err)
	}

	return &m, nil
}

// Save writes a ProjectManifest to the given path as YAML, preceded by a
// header comment. Parent directories are created if they do not exist.
func Save(path string, m *ProjectManifest) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	data, err := yaml.Marshal(m)
	if err != nil {
		return fmt.Errorf("failed to marshal manifest: %w", err)
	}

	content := []byte(headerComment)
	content = append(content, data...)

	if err := os.WriteFile(path, content, 0644); err != nil {
		return fmt.Errorf("failed to write manifest: %w", err)
	}

	return nil
}
