// Package lockfile manages the code-minions.lock file that records
// exact resolved versions for all dependencies. The lockfile
// guarantees reproducible installs: two developers (or a developer
// and CI) resolve the same package versions when the lockfile is
// committed to version control.
//
// The lockfile sits alongside code-minions.yml and complements it:
//   - code-minions.yml = desired state ("I want these packages")
//   - code-minions.lock = resolved state ("these exact versions")
package lockfile

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"gopkg.in/yaml.v3"
)

const (
	// FileName is the default lockfile filename.
	FileName = "code-minions.lock"

	// CurrentVersion is the lockfile schema version.
	CurrentVersion = 1

	// headerComment is prepended to the YAML output.
	headerComment = "# code-minions.lock — DO NOT EDIT MANUALLY\n# Generated by code-minions install\n"

	// TypeBuiltin identifies packages embedded in the CLI binary.
	TypeBuiltin = "builtin"

	// TypeRemote identifies packages fetched from a Git source.
	TypeRemote = "remote"
)

// LockFile represents the complete lockfile contents.
type LockFile struct {
	// LockfileVersion is the schema version (currently 1).
	LockfileVersion int `yaml:"lockfile_version"`

	// GeneratedAt is the UTC timestamp when the lockfile was generated.
	GeneratedAt string `yaml:"generated_at"`

	// CLIVersion is the version of the CLI that generated this lockfile.
	CLIVersion string `yaml:"cli_version"`

	// Packages maps package identifiers to their resolved state.
	// Keys are package names for builtins, source URLs for remotes.
	Packages map[string]LockedPackage `yaml:"packages"`
}

// LockedPackage records the resolved state of a single package.
type LockedPackage struct {
	// Type is "builtin" (embedded in CLI) or "remote" (fetched from Git).
	Type string `yaml:"type"`

	// Version is the version string at resolution time.
	// For builtins, this is the CLI version that bundled it.
	Version string `yaml:"version"`

	// Source is the source URL or name (remote packages only).
	Source string `yaml:"source,omitempty"`

	// Resolved is the exact Git commit SHA (remote packages only).
	Resolved string `yaml:"resolved,omitempty"`

	// Integrity is the content hash in "sha256:<hex>" format (remote only).
	Integrity string `yaml:"integrity,omitempty"`

	// Direct is true when the package was explicitly listed in the manifest.
	Direct bool `yaml:"direct"`

	// DependencyOf lists parent packages (transitive dependencies only).
	DependencyOf []string `yaml:"dependency_of,omitempty"`
}

// New creates a fresh LockFile with the given CLI version and current timestamp.
func New(cliVersion string) *LockFile {
	return &LockFile{
		LockfileVersion: CurrentVersion,
		GeneratedAt:     time.Now().UTC().Format(time.RFC3339),
		CLIVersion:      cliVersion,
		Packages:        make(map[string]LockedPackage),
	}
}

// DefaultPath returns the full path to code-minions.lock within the
// given target directory.
func DefaultPath(target string) string {
	return filepath.Join(target, FileName)
}

// Exists checks whether a lockfile exists at the given path.
// Returns (true, nil) if the file exists, (false, nil) if it does not,
// or (false, err) if the check failed (e.g. permission denied).
func Exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if os.IsNotExist(err) {
		return false, nil
	}
	return false, fmt.Errorf("failed to check lockfile: %w", err)
}

// Load reads and parses a lockfile from disk.
// Returns (nil, nil) if the file does not exist — callers should
// treat this as "no lockfile yet, resolve from scratch".
func Load(path string) (*LockFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to read lockfile: %w", err)
	}

	var lf LockFile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("failed to parse lockfile: %w", err)
	}

	if lf.Packages == nil {
		lf.Packages = make(map[string]LockedPackage)
	}

	// Reject lockfiles from future schema versions that this CLI
	// cannot safely interpret. Users should upgrade their CLI.
	if lf.LockfileVersion > CurrentVersion {
		return nil, fmt.Errorf(
			"lockfile version %d is newer than supported version %d — please upgrade code-minions",
			lf.LockfileVersion, CurrentVersion,
		)
	}

	return &lf, nil
}

// Save writes the lockfile atomically (temp file + rename).
// Follows the same pattern as manifest.Save() to avoid leaving
// a partially-written lockfile if the process is interrupted.
func Save(path string, lf *LockFile) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	data, err := marshalSorted(lf)
	if err != nil {
		return fmt.Errorf("failed to marshal lockfile: %w", err)
	}

	content := []byte(headerComment)
	content = append(content, data...)

	// Atomic write: temp file in same dir, then rename into place.
	tmpFile, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return fmt.Errorf("failed to create temporary lockfile: %w", err)
	}
	tmpPath := tmpFile.Name()

	if _, err := tmpFile.Write(content); err != nil {
		_ = tmpFile.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write lockfile: %w", err)
	}
	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write lockfile: %w", err)
	}

	// On Windows, os.Rename fails if the destination already exists.
	// Use a backup-and-restore strategy to avoid data loss.
	backupPath := path + ".bak"
	hadBackup := false
	if err := os.Rename(path, backupPath); err != nil {
		if !os.IsNotExist(err) {
			_ = os.Remove(tmpPath)
			return fmt.Errorf("failed to prepare lockfile backup: %w", err)
		}
	} else {
		hadBackup = true
	}

	if err := os.Rename(tmpPath, path); err != nil {
		if hadBackup {
			_ = os.Rename(backupPath, path)
		}
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write lockfile: %w", err)
	}

	if hadBackup {
		_ = os.Remove(backupPath)
	}

	return nil
}

// Merge adds or updates entries in the lockfile for the given packages,
// preserving existing entries for unchanged packages.
func (lf *LockFile) Merge(updates map[string]LockedPackage) {
	for k, v := range updates {
		lf.Packages[k] = v
	}
}

// Prune removes entries from the lockfile that are not in the
// provided keep set. The keep set should contain all package keys
// that are still relevant (manifest packages + their transitive deps).
func (lf *LockFile) Prune(keep map[string]bool) {
	for k := range lf.Packages {
		if !keep[k] {
			delete(lf.Packages, k)
		}
	}
}

// PackageNames returns a sorted list of all package keys in the lockfile.
func (lf *LockFile) PackageNames() []string {
	names := make([]string, 0, len(lf.Packages))
	for k := range lf.Packages {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}

// marshalSorted marshals the lockfile with packages in sorted key order
// for deterministic output. This ensures that two lockfiles with identical
// content always produce byte-identical YAML.
func marshalSorted(lf *LockFile) ([]byte, error) {
	// Build a YAML node tree so we control key ordering.
	doc := &yaml.Node{Kind: yaml.MappingNode}

	addScalar(doc, "lockfile_version", fmt.Sprintf("%d", lf.LockfileVersion))
	addScalar(doc, "generated_at", lf.GeneratedAt)
	addScalar(doc, "cli_version", lf.CLIVersion)

	// Build sorted packages map
	pkgMap := &yaml.Node{Kind: yaml.MappingNode}
	names := lf.PackageNames()
	for _, name := range names {
		pkg := lf.Packages[name]

		pkgNode := &yaml.Node{Kind: yaml.MappingNode}
		addScalar(pkgNode, "type", pkg.Type)
		addScalar(pkgNode, "version", pkg.Version)

		if pkg.Source != "" {
			addScalar(pkgNode, "source", pkg.Source)
		}
		if pkg.Resolved != "" {
			addScalar(pkgNode, "resolved", pkg.Resolved)
		}
		if pkg.Integrity != "" {
			addScalar(pkgNode, "integrity", pkg.Integrity)
		}

		addScalar(pkgNode, "direct", fmt.Sprintf("%t", pkg.Direct))

		if len(pkg.DependencyOf) > 0 {
			depOfKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "dependency_of"}
			depOfSeq := &yaml.Node{Kind: yaml.SequenceNode}
			sorted := make([]string, len(pkg.DependencyOf))
			copy(sorted, pkg.DependencyOf)
			sort.Strings(sorted)
			for _, dep := range sorted {
				depOfSeq.Content = append(depOfSeq.Content, &yaml.Node{
					Kind:  yaml.ScalarNode,
					Value: dep,
				})
			}
			pkgNode.Content = append(pkgNode.Content, depOfKey, depOfSeq)
		}

		nameNode := &yaml.Node{Kind: yaml.ScalarNode, Value: name}
		pkgMap.Content = append(pkgMap.Content, nameNode, pkgNode)
	}

	pkgKey := &yaml.Node{Kind: yaml.ScalarNode, Value: "packages"}
	doc.Content = append(doc.Content, pkgKey, pkgMap)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// addScalar appends a key-value pair of scalar nodes to a mapping node.
func addScalar(mapping *yaml.Node, key, value string) {
	mapping.Content = append(mapping.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value},
	)
}
