package cmd

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/fatih/color"
	"github.com/willvelida/code-minions/internal/model"
	"gopkg.in/yaml.v3"
)

// testContentFSForTeam builds a minimal embedded filesystem for team tests.
func testContentFSForTeam() fstest.MapFS {
	return fstest.MapFS{
		"packages/git-workflow/package.yaml": &fstest.MapFile{
			Data: []byte("name: git-workflow\nversion: 0.1.0\ndescription: Git workflow conventions\n"),
		},
		"packages/git-workflow/agents/git-workflow.agent.md": &fstest.MapFile{
			Data: []byte("# Git Agent"),
		},
		"packages/developer-mentor/package.yaml": &fstest.MapFile{
			Data: []byte("name: developer-mentor\nversion: 0.1.0\ndescription: Developer mentoring skill\n"),
		},
		"packages/developer-mentor/agents/developer-mentor.agent.md": &fstest.MapFile{
			Data: []byte("# Mentor Agent"),
		},
		"packages/threat-modelling/package.yaml": &fstest.MapFile{
			Data: []byte("name: threat-modelling\nversion: 0.1.0\ndescription: STRIDE-based threat modelling\n"),
		},
		"packages/threat-modelling/agents/threat-modelling.agent.md": &fstest.MapFile{
			Data: []byte("# Threat Agent"),
		},
	}
}

func TestTeamInitCreatesTeamYAML(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "test-team"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify file was created
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	// Verify header comment
	if !strings.HasPrefix(string(data), "# Generated by code-minions team init") {
		t.Error("expected header comment")
	}

	// Parse and verify content
	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}
	if team.Name != "test-team" {
		t.Errorf("Name: got %q, want %q", team.Name, "test-team")
	}
	if len(team.Personas) == 0 {
		t.Error("expected at least one persona")
	}
	if team.Config.DefaultAssistant != "copilot" {
		t.Errorf("DefaultAssistant: got %q, want %q", team.Config.DefaultAssistant, "copilot")
	}

	// Verify the output contains success message
	if !strings.Contains(buf.String(), "Created") {
		t.Error("expected success message in output")
	}
}

func TestTeamInitWithFlags(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{
		"team", "init",
		"--output", outputPath,
		"--yes",
		"--name", "platform",
		"--description", "Platform team",
		"--assistant", "claude",
		"--enforce-packages",
	})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}

	if team.Name != "platform" {
		t.Errorf("Name: got %q, want %q", team.Name, "platform")
	}
	if team.Description != "Platform team" {
		t.Errorf("Description: got %q, want %q", team.Description, "Platform team")
	}
	if team.Config.DefaultAssistant != "claude" {
		t.Errorf("DefaultAssistant: got %q, want %q", team.Config.DefaultAssistant, "claude")
	}
	if !team.Config.EnforcePackages {
		t.Error("EnforcePackages: got false, want true")
	}
}

func TestTeamInitRefusesOverwrite(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	// Create an existing file
	if err := os.WriteFile(outputPath, []byte("name: existing\n"), 0644); err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "test"})

	err := root.Execute()
	if err == nil {
		t.Fatal("expected error for existing file")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Errorf("error %q should mention 'already exists'", err.Error())
	}
}

func TestTeamInitForceOverwrites(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	// Create an existing file
	if err := os.WriteFile(outputPath, []byte("name: existing\n"), 0644); err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "new-team", "--force"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Verify file was overwritten
	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}
	if team.Name != "new-team" {
		t.Errorf("Name: got %q, want %q (file was not overwritten)", team.Name, "new-team")
	}
}

func TestTeamInitJSON(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "json-team", "--json"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	var result teamInitResult
	if err := json.Unmarshal(buf.Bytes(), &result); err != nil {
		t.Fatalf("failed to parse JSON output: %v\nOutput: %s", err, buf.String())
	}

	if result.Name != "json-team" {
		t.Errorf("Name: got %q, want %q", result.Name, "json-team")
	}
	if result.TeamPath != "team.yaml" {
		t.Errorf("TeamPath: got %q, want %q", result.TeamPath, "team.yaml")
	}
	if result.Assistant != "copilot" {
		t.Errorf("Assistant: got %q, want %q", result.Assistant, "copilot")
	}
	if len(result.Personas) == 0 {
		t.Error("expected at least one persona in JSON output")
	}
	if len(result.Personas[0].Packages) == 0 {
		t.Error("expected persona to have packages")
	}
}

func TestTeamInitHeaderComment(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "my-team"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	if !strings.HasPrefix(string(data), teamHeaderComment) {
		t.Errorf("expected file to start with %q, got %q", teamHeaderComment, string(data)[:50])
	}
}

func TestTeamInitEnforcePackages(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "strict-team", "--enforce-packages"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}
	if !team.Config.EnforcePackages {
		t.Error("EnforcePackages: got false, want true")
	}
}

func TestTeamInitOutputFlag(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "config", "my-team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "custom-path"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(outputPath); err != nil {
		t.Fatalf("expected file at custom path %q: %v", outputPath, err)
	}
}

func TestTeamInitDefaultPersona(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "default-test"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}

	// Non-interactive should create one "default" persona with all packages
	if len(team.Personas) != 1 {
		t.Fatalf("Personas: got %d, want 1", len(team.Personas))
	}
	if team.Personas[0].Name != "default" {
		t.Errorf("Persona name: got %q, want %q", team.Personas[0].Name, "default")
	}
	// Should have all 3 test packages
	if len(team.Personas[0].Packages) != 3 {
		t.Errorf("Persona packages: got %d, want 3", len(team.Personas[0].Packages))
	}
}

func TestTeamInitNameValidation(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetErr(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "my-->team"})

	err := root.Execute()
	if err == nil {
		t.Fatal("expected error for invalid team name")
	}
	if !strings.Contains(err.Error(), "invalid characters") {
		t.Errorf("error %q should mention 'invalid characters'", err.Error())
	}
}

func TestTeamInitDefaultDescription(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "my-team"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}
	if team.Description != "Team configuration for my-team" {
		t.Errorf("Description: got %q, want %q", team.Description, "Team configuration for my-team")
	}
}

func TestTeamInitPersonaPackagesInYAML(t *testing.T) {
	color.NoColor = true
	t.Cleanup(func() { color.NoColor = false })

	origInteractive := isInteractiveFunc
	isInteractiveFunc = func() bool { return false }
	t.Cleanup(func() { isInteractiveFunc = origInteractive })

	dir := t.TempDir()
	content := testContentFSForTeam()
	outputPath := filepath.Join(dir, "team.yaml")

	var buf bytes.Buffer
	root := NewRootCommand(content)
	root.SetOut(&buf)
	root.SetArgs([]string{"team", "init", "--output", outputPath, "--yes", "--name", "pkg-test"})

	if err := root.Execute(); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	data, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("failed to read team.yaml: %v", err)
	}

	// Verify the YAML contains packages under personas
	if !strings.Contains(string(data), "packages:") {
		t.Error("expected YAML to contain 'packages:' field under personas")
	}

	// Verify round-trip
	var team model.Team
	if err := yaml.Unmarshal(data, &team); err != nil {
		t.Fatalf("failed to parse team.yaml: %v", err)
	}
	for _, persona := range team.Personas {
		if len(persona.Packages) == 0 {
			t.Errorf("persona %q should have packages", persona.Name)
		}
	}
}

func TestBuildPersonaResults(t *testing.T) {
	personas := []model.PersonaRef{
		{
			Name: "dev",
			Packages: []model.PackageRef{
				{Name: "git-workflow"},
				{Name: "developer-mentor"},
			},
		},
		{
			Name:     "reviewer",
			Packages: []model.PackageRef{},
		},
	}

	results := buildPersonaResults(personas)
	if len(results) != 2 {
		t.Fatalf("got %d results, want 2", len(results))
	}
	if results[0].Name != "dev" {
		t.Errorf("results[0].Name: got %q", results[0].Name)
	}
	if len(results[0].Packages) != 2 {
		t.Errorf("results[0].Packages: got %d, want 2", len(results[0].Packages))
	}
	// Empty packages should produce empty slice, not nil
	if results[1].Packages == nil {
		t.Error("expected empty slice, not nil")
	}
}

func TestFormatPersonaSummary(t *testing.T) {
	personas := []model.PersonaRef{
		{
			Name:     "dev",
			Packages: []model.PackageRef{{Name: "a"}, {Name: "b"}, {Name: "c"}},
		},
		{
			Name:     "reviewer",
			Packages: []model.PackageRef{{Name: "a"}},
		},
	}

	got := formatPersonaSummary(personas)
	if !strings.Contains(got, "dev (3 packages)") {
		t.Errorf("expected 'dev (3 packages)' in %q", got)
	}
	if !strings.Contains(got, "reviewer (1 package)") {
		t.Errorf("expected 'reviewer (1 package)' in %q", got)
	}
}
