package cmd

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
	"github.com/willvelida/code-minions/internal/model"
	"github.com/willvelida/code-minions/internal/registry"
	"gopkg.in/yaml.v3"
)

const teamHeaderComment = "# Generated by code-minions team init\n"

func newTeamCommand(content fs.FS) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "team",
		Short: "Manage team configurations",
		Long: `Commands for creating and managing team configurations.

Teams are named groupings of personas — each persona carries a curated
set of packages. Team leads use teams to standardise which coding
assistant configurations their team members install.`,
	}

	cmd.AddCommand(newTeamInitCommand(content))

	return cmd
}

// teamInitOptions bundles all the resolved flags for the team init command.
type teamInitOptions struct {
	nameFlag        string
	descriptionFlag string
	assistantFlag   string
	outputFlag      string
	enforcePackages bool
	fromFlag        string
	yes             bool
	force           bool
	mode            OutputMode
}

// teamInitResult is the JSON output for the team init command.
type teamInitResult struct {
	TeamPath        string          `json:"team_path"`
	Name            string          `json:"name"`
	Description     string          `json:"description"`
	Assistant       string          `json:"assistant"`
	EnforcePackages bool            `json:"enforce_packages"`
	Personas        []personaResult `json:"personas"`
}

// personaResult is a persona entry in the JSON output.
type personaResult struct {
	Name     string   `json:"name"`
	Packages []string `json:"packages"`
}

func newTeamInitCommand(content fs.FS) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a team.yaml configuration interactively",
		Long: `Create a team.yaml team configuration file using an interactive wizard.

The wizard guides you through defining a team name, description, default
assistant, and one or more personas. Each persona is assigned a curated
set of packages from the available registry.

In non-interactive mode (--yes flag or non-TTY stdin), sensible defaults
are used: the team name is derived from the current directory, and a
single persona is created with all available packages.`,
		Example: `  # Interactive wizard
  code-minions team init

  # Non-interactive with defaults
  code-minions team init --yes

  # Specify all values via flags
  code-minions team init --name platform --description "Platform team" --assistant copilot --yes

  # Custom output path
  code-minions team init --output config/team.yaml

  # Overwrite existing team.yaml
  code-minions team init --force

  # JSON output for scripting
  code-minions team init --name my-team --yes --json`,
		RunE: func(cmd *cobra.Command, args []string) error {
			nameFlag, _ := cmd.Flags().GetString("name")
			descriptionFlag, _ := cmd.Flags().GetString("description")
			assistantFlag, _ := cmd.Flags().GetString("assistant")
			outputFlag, _ := cmd.Flags().GetString("output")
			enforcePackages, _ := cmd.Flags().GetBool("enforce-packages")
			fromFlag, _ := cmd.Flags().GetString("from")
			yesFlag, _ := cmd.Flags().GetBool("yes")
			forceFlag, _ := cmd.Flags().GetBool("force")

			mode := getOutputMode(cmd)

			return runTeamInit(cmd, content, teamInitOptions{
				nameFlag:        nameFlag,
				descriptionFlag: descriptionFlag,
				assistantFlag:   assistantFlag,
				outputFlag:      outputFlag,
				enforcePackages: enforcePackages,
				fromFlag:        fromFlag,
				yes:             yesFlag,
				force:           forceFlag,
				mode:            mode,
			})
		},
	}

	cmd.Flags().String("name", "", "Team name (skip prompt)")
	cmd.Flags().String("description", "", "Team description (skip prompt)")
	cmd.Flags().String("assistant", "", "Default assistant (skip prompt)")
	cmd.Flags().String("output", "team.yaml", "Output file path")
	cmd.Flags().Bool("enforce-packages", false, "Set enforce_packages in team config")
	cmd.Flags().String("from", "", "Package source name or Git URL")
	cmd.Flags().BoolP("yes", "y", false, "Accept defaults without prompting")
	cmd.Flags().Bool("force", false, "Overwrite existing team.yaml")

	return cmd
}

func runTeamInit(cmd *cobra.Command, content fs.FS, opts teamInitOptions) error {
	// --- Step 1: Check if output file exists ---
	outputPath := opts.outputFlag
	if !filepath.IsAbs(outputPath) {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("failed to get working directory: %w", err)
		}
		outputPath = filepath.Join(cwd, outputPath)
	}

	if _, err := os.Stat(outputPath); err == nil && !opts.force {
		return fmt.Errorf("%s already exists\n\nUse --force to overwrite", opts.outputFlag)
	}

	// --- Step 2: Build registry and list packages ---
	var reg *registry.Registry
	var err error
	if opts.fromFlag != "" {
		reg, err = registry.BuildRegistryWithFrom(content, opts.fromFlag)
	} else {
		reg, err = registry.BuildRegistry(content)
	}
	if err != nil {
		return fmt.Errorf("failed to build registry: %w", err)
	}

	packages, err := reg.ListPackages()
	if err != nil {
		return fmt.Errorf("failed to list packages: %w", err)
	}
	verbosePrintf(cmd, opts.mode, "found %d packages\n", len(packages))

	// Determine whether we're interactive
	interactive := isInteractiveFunc() && !opts.yes && opts.mode != OutputJSON && opts.mode != OutputQuiet

	// --- Step 3: Resolve team name ---
	teamName, err := resolveTeamName(cmd, opts, interactive)
	if err != nil {
		return err
	}
	verbosePrintf(cmd, opts.mode, "team name: %s\n", teamName)

	// --- Step 4: Resolve team description ---
	teamDesc, err := resolveTeamDescription(cmd, opts, teamName, interactive)
	if err != nil {
		return err
	}
	verbosePrintf(cmd, opts.mode, "team description: %s\n", teamDesc)

	// --- Step 5: Resolve default assistant ---
	assistant, err := resolveTeamAssistant(cmd, opts, interactive)
	if err != nil {
		return err
	}
	verbosePrintf(cmd, opts.mode, "default assistant: %s\n", assistant)

	// --- Step 6: Resolve enforce_packages ---
	enforcePackages, err := resolveEnforcePackages(cmd, opts, interactive)
	if err != nil {
		return err
	}

	// --- Step 7: Build personas ---
	personas, err := resolvePersonas(cmd, opts, packages, interactive)
	if err != nil {
		return err
	}

	// --- Step 8: Build Team struct ---
	team := &model.Team{
		Name:        teamName,
		Description: teamDesc,
		Personas:    personas,
		Config: model.TeamConfig{
			DefaultAssistant: assistant,
			EnforcePackages:  enforcePackages,
		},
	}

	// --- Step 9: Validate ---
	if err := model.ValidateTeam(team); err != nil {
		return err
	}

	// --- Step 10: Write team.yaml ---
	if err := writeTeamYAML(outputPath, team); err != nil {
		return err
	}

	// --- Step 11: Output ---
	result := teamInitResult{
		TeamPath:        filepath.Base(outputPath),
		Name:            teamName,
		Description:     teamDesc,
		Assistant:       assistant,
		EnforcePackages: enforcePackages,
		Personas:        buildPersonaResults(personas),
	}

	if opts.mode == OutputJSON {
		return json.NewEncoder(cmd.OutOrStdout()).Encode(result)
	}

	if opts.mode != OutputQuiet {
		out := cmd.OutOrStdout()
		bold := color.New(color.Bold)
		green := color.New(color.FgGreen)

		_, _ = green.Fprintf(out, "✓ Created %s\n", filepath.Base(outputPath))
		_, _ = fmt.Fprintln(out)
		_, _ = bold.Fprintf(out, "  Team:     %s\n", teamName)
		_, _ = bold.Fprintf(out, "  Personas: %s\n", formatPersonaSummary(personas))
		_, _ = fmt.Fprintln(out)
	}

	return nil
}

// resolveTeamName determines the team name from flags, defaults, or prompts.
func resolveTeamName(cmd *cobra.Command, opts teamInitOptions, interactive bool) (string, error) {
	if opts.nameFlag != "" {
		return opts.nameFlag, nil
	}

	if !interactive {
		cwd, err := os.Getwd()
		if err != nil {
			return "", fmt.Errorf("failed to get working directory: %w", err)
		}
		return sanitizeTeamName(filepath.Base(cwd)), nil
	}

	return promptTeamName(cmd.InOrStdin(), cmd.OutOrStdout())
}

// resolveTeamDescription determines the team description from flags, defaults, or prompts.
func resolveTeamDescription(cmd *cobra.Command, opts teamInitOptions, teamName string, interactive bool) (string, error) {
	if opts.descriptionFlag != "" {
		return opts.descriptionFlag, nil
	}

	if !interactive {
		return fmt.Sprintf("Team configuration for %s", teamName), nil
	}

	return promptTeamDescription(cmd.InOrStdin(), cmd.OutOrStdout())
}

// resolveTeamAssistant determines the default assistant from flags, defaults, or prompts.
func resolveTeamAssistant(cmd *cobra.Command, opts teamInitOptions, interactive bool) (string, error) {
	if opts.assistantFlag != "" {
		return opts.assistantFlag, nil
	}

	if !interactive {
		return "copilot", nil
	}

	return promptAssistant(cmd.InOrStdin(), cmd.OutOrStdout())
}

// resolveEnforcePackages determines the enforce_packages setting from flags or prompts.
func resolveEnforcePackages(cmd *cobra.Command, opts teamInitOptions, interactive bool) (bool, error) {
	// If the flag was explicitly set on the command line, use it
	if cmd.Flags().Changed("enforce-packages") {
		return opts.enforcePackages, nil
	}

	if !interactive {
		return false, nil
	}

	return confirmPrompt(cmd.InOrStdin(), cmd.OutOrStdout(), "Enforce packages? (y/N) ")
}

// resolvePersonas builds the persona list from flags, defaults, or prompts.
func resolvePersonas(cmd *cobra.Command, opts teamInitOptions, packages []model.Package, interactive bool) ([]model.PersonaRef, error) {
	if !interactive {
		// Non-interactive: create one persona named "default" with all packages
		pkgRefs := make([]model.PackageRef, len(packages))
		for i, pkg := range packages {
			pkgRefs[i] = model.PackageRef{Name: pkg.Name}
		}
		return []model.PersonaRef{
			{
				Name:     "default",
				Packages: pkgRefs,
			},
		}, nil
	}

	// Interactive: persona loop
	var personas []model.PersonaRef
	first := true

	for {
		prompt := "Add another persona? (Y/n) "
		if first {
			prompt = "Add a persona? (Y/n) "
		}

		ok, err := confirmPrompt(cmd.InOrStdin(), cmd.OutOrStdout(), prompt)
		if err != nil {
			return nil, err
		}

		// For the first prompt, default to yes (treat non-"n" as yes)
		if first && !ok {
			// confirmPrompt returns false for empty input; for "Add a persona?"
			// we treat empty as yes since a team needs at least one persona.
			// Re-check: only skip if user explicitly said no.
			// Actually, confirmPrompt treats empty as "no". Let's just
			// always add the first persona since a team needs at least one.
		}

		if !first && !ok {
			break
		}
		first = false

		// Prompt for persona name
		name, err := promptPersonaName(cmd.InOrStdin(), cmd.OutOrStdout())
		if err != nil {
			return nil, err
		}

		// Prompt for package selection
		selected, err := selectPackages(cmd.InOrStdin(), cmd.OutOrStdout(), packages)
		if err != nil {
			return nil, err
		}

		pkgRefs := make([]model.PackageRef, len(selected))
		for i, s := range selected {
			pkgRefs[i] = model.PackageRef{Name: s}
		}

		personas = append(personas, model.PersonaRef{
			Name:     name,
			Packages: pkgRefs,
		})
	}

	if len(personas) == 0 {
		return nil, fmt.Errorf("at least one persona is required")
	}

	return personas, nil
}

// writeTeamYAML marshals a Team to YAML and writes it atomically.
func writeTeamYAML(path string, team *model.Team) error {
	data, err := yaml.Marshal(team)
	if err != nil {
		return fmt.Errorf("failed to marshal team: %w", err)
	}

	content := []byte(teamHeaderComment)
	content = append(content, data...)

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Atomic write: temp file + rename
	tmpFile, err := os.CreateTemp(dir, ".team-*.yaml")
	if err != nil {
		return fmt.Errorf("failed to create temporary file: %w", err)
	}
	tmpPath := tmpFile.Name()

	if _, err := tmpFile.Write(content); err != nil {
		_ = tmpFile.Close()
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write team file: %w", err)
	}
	if err := tmpFile.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write team file: %w", err)
	}

	// On Windows, os.Rename fails if the destination already exists.
	backupPath := path + ".bak"
	hadBackup := false
	if err := os.Rename(path, backupPath); err != nil {
		if !os.IsNotExist(err) {
			_ = os.Remove(tmpPath)
			return fmt.Errorf("failed to prepare backup: %w", err)
		}
	} else {
		hadBackup = true
	}

	if err := os.Rename(tmpPath, path); err != nil {
		if hadBackup {
			_ = os.Rename(backupPath, path)
		}
		_ = os.Remove(tmpPath)
		return fmt.Errorf("failed to write team file: %w", err)
	}

	if hadBackup {
		_ = os.Remove(backupPath)
	}

	return nil
}

// buildPersonaResults converts PersonaRefs to personaResults for JSON output.
func buildPersonaResults(personas []model.PersonaRef) []personaResult {
	results := make([]personaResult, len(personas))
	for i, p := range personas {
		pkgs := make([]string, len(p.Packages))
		for j, pkg := range p.Packages {
			pkgs[j] = pkg.Name
		}
		results[i] = personaResult{
			Name:     p.Name,
			Packages: nonNil(pkgs),
		}
	}
	return results
}

// formatPersonaSummary returns a human-readable summary of personas.
func formatPersonaSummary(personas []model.PersonaRef) string {
	parts := make([]string, len(personas))
	for i, p := range personas {
		parts[i] = fmt.Sprintf("%s (%d packages)", p.Name, len(p.Packages))
	}
	return strings.Join(parts, ", ")
}

// sanitizeTeamName converts a directory name into a valid team name.
func sanitizeTeamName(name string) string {
	// Replace spaces and dots with hyphens
	name = strings.ReplaceAll(name, " ", "-")
	name = strings.ReplaceAll(name, ".", "-")

	// Remove any characters that don't match the pattern
	var result strings.Builder
	for _, r := range name {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			result.WriteRune(r)
		}
	}

	sanitized := result.String()
	if sanitized == "" {
		return "my-team"
	}

	// Ensure it starts with alphanumeric
	if sanitized[0] == '-' || sanitized[0] == '_' {
		sanitized = "t" + sanitized
	}

	return sanitized
}
